#
# Veracode pipeline for Azure showing Veracode ABS and Veracode SAST Policy Scan and Import of Veracode Issues

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  displayName: 'build verademo'
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-q'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
  
- task: Bash@3
  displayName: 'Veracode SCA scan'
  inputs:
     targetType: 'inline'
     script: |
          export SRCCLR_SCM_URI=https://github.com/christyson/verademo
          export SRCCLR_API_TOKEN="$(SRCCLR_API_TOKEN)"
          export SRCCLR_SCM_REF=master
          export SRCCLR_SCM_REF_TYPE=branch
          export SRCCLR_SCM_REV="$(build.buildNumber)"
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s -- scan --update-advisor
  continueOnError: true
  env:
    SRCCLR_API_TOKEN: $(SRCCLR_API_TOKEN)

- task: Veracode@3
  displayName: Veracode Static Scan 
  inputs:
    ConnectionDetailsSelection: 'Endpoint'
    AnalysisService: 'Veracode2'
    veracodeAppProfile: 'AzureDevOps-VeraDemo_pipeline'
    version: '$(build.buildNumber)'
    filepath: '/home/vsts/work/1/s/target/verademo.war'
    createProfile: true
    scanStatusCheckInterval: '60'
    importResults: true
    failBuildOnPolicyFail: false

- task: Veracode Flaw Importer@3
  displayName: Veracode Flaw Import
  inputs:
    ConnectionDetailsSelection: 'Endpoint'
    AnalysisService: 'Veracode2'
    veracodeAppProfile: 'AzureDevOps-VeraDemo_pipeline'
    sandboxName: 
    importType: 'All Unmitigated Flaws Violating Policy'
    workItemType: 'Issue'
    area: '$(system.teamProject)'
    addCustomTag: 'Veracode'
    flawImportLimit: '10000'
